// Bake structure anchor transforms (element_XX, call_anchor, fragment_anchor)
// out of the glTF files into app/field/structure-anchors.json so the game logic
// can run without a renderer or a browser. Run after the models change.
import http from "node:http";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
const { chromium } = createRequire(import.meta.url)(path.join(process.env.NPM_GLOBAL_ROOT ?? "/home/claude/.npm-global/lib/node_modules", "playwright"));

const root = process.cwd();
const types = { ".html": "text/html", ".js": "text/javascript", ".mjs": "text/javascript", ".json": "application/json", ".glb": "model/gltf-binary" };
const server = http.createServer(async (req, res) => {
  const pathname = decodeURIComponent(new URL(req.url, "http://x").pathname);
  let body = null, file = path.join(root, pathname);
  try { body = await readFile(file); } catch { try { file = path.join(root, "public", pathname); body = await readFile(file); } catch { body = null; } }
  if (body === null) { res.writeHead(404); res.end(); return; }
  res.writeHead(200, { "content-type": types[path.extname(file)] ?? "application/octet-stream" }); res.end(body);
});
await new Promise(resolve => server.listen(4182, resolve));
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--no-sandbox"] });
const page = await browser.newPage();
page.on("console", m => console.log("[browser]", m.text()));
page.on("pageerror", e => console.log("[pageerror]", e.message));
await page.goto("http://localhost:4182/scripts/bake-anchors.html");
await page.waitForFunction(() => window.__anchors, null, { timeout: 120_000 });
const anchors = await page.evaluate(() => window.__anchors);
// A TypeScript module rather than a JSON import, so Node's type stripping and Vite both load it without import attributes.
const compact = Object.fromEntries(Object.entries(anchors).map(([id, v]) => [id, { bounds: v.bounds, anchors: v.anchors.map(a => ({ name: a.name, position: a.position, gesture: a.extras.gesture ?? null, noteHz: a.extras.noteHz ?? null, radius: a.extras.radius ?? null })) }]));
await writeFile("app/field/structure-anchors.ts", `// Generated by scripts/bake-anchors.mjs from public/fog/models/*.glb. Do not edit by hand.\nexport type BakedAnchor = { name: string; position: [number, number, number]; gesture: "approach" | "look" | "listen" | null; noteHz: number | null; radius: number | null };\nexport type BakedModel = { bounds: [[number, number, number], [number, number, number]]; anchors: BakedAnchor[] };\nexport const STRUCTURE_ANCHORS: Record<string, BakedModel> = ${JSON.stringify(compact)};\n`);
console.log(Object.entries(anchors).map(([id, v]) => `${id}: ${v.anchors.map(a => a.name + (a.extras.gesture ? `(${a.extras.gesture})` : "")).join(" ")} | materials ${v.materials.join(",")} | meshes ${v.nodes.join(",")}`).join("\n"));
await browser.close(); server.close();
